Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 2: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 4, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 6: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 4: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 5: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 2: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 1, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 0, 1)
Redundant EST message received by 7: ('EST', 2, 1)
Redundant EST message received by 1: ('EST', 0, 1)
Redundant EST message received by 3: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 3: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 3: ('EST', 6, 1)
Redundant EST message received by 0: ('EST', 5, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 0: ('EST', 7, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 4: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 5: ('EST', 0, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 2, 1)
Redundant EST message received by 5: ('EST', 2, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 5: ('EST', 3, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
Redundant EST message received by 0: ('EST', 4, 1)
Redundant EST message received by 5: ('EST', 4, 1)
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Redundant EST message received by 5: ('EST', 4, 1)
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 216, in send
    self._send(j, pickle.dumps(o))
TypeError: can't pickle pairing.Element objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 219, in send
    (a, (h1, r, (h2, b, e))) = o
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 228, in send
    (h2, b, e) = o
ValueError: not enough values to unpack (expected 3, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 200, in _send
    self.socks[j].sendall(msg)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 374, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py", line 303, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 205, in _send
    self._connect(j)
  File "/home/yylluu/Workspace/HoneyBadgerBFT-Python/myexperiements/mysockettest/badger_socket_node.py", line 177, in _connect
    sock.bind(("", self.port + 10 * j + 1))
OSError: [Errno 98] Address already in use
[('127.0.0.1', 20000), ('127.0.0.1', 20200), ('127.0.0.1', 20400), ('127.0.0.1', 20600), ('127.0.0.1', 20800), ('127.0.0.1', 21000), ('127.0.0.1', 21200), ('127.0.0.1', 21400)]
PK of Thld Sig is depickled
PK of Thld Enc is depickled
SK of Thld Sig is depickled
SK of Thld Enc is depickled
